Ditmar/OpenScience

src/globals/_variables.scss, src/ui/components/atoms/publish-button/PublishButton.stories.tsx, src/ui/components/atoms/publish-button/PublishButton.test.jsx, src/ui/components/atoms/publish-button/PublishButton.tsx, src/ui/components/atoms/publish-button/styles.scss, src/ui/components/atoms/publish-button/types/IProps.ts
Como usuario del sistema, quiero un componente de botón que me permita publicar un artículo de manera rápida y sencilla, para poder compartir contenido con otros usuarios de la plataforma.
=> fix: once again SEM-040

.github/workflows/publish-storybook.yml, .gitignore, .prettierignore, .stylelintrc.json, vite.config.ts
added storybook pipeline publisher
=> feat: added pipeline and prettier ignorefile

package.json, src/ui/components/atoms/Tags/Tags.stories.tsx, src/ui/components/atoms/Tags/Tags.test.tsx, src/ui/components/atoms/Tags/Tags.tsx, src/ui/components/atoms/Tags/styles.scss, src/ui/components/atoms/Tags/types/IProps.ts, yarn.lock
Como usuario quiero mostrar diferentes tags en un articulo.
=> [SEM-056] TAGS

src/assets/icons/burger-menu.svg, src/ui/components/atoms/button-burger/ButtonBurger.stories.tsx, src/ui/components/atoms/button-burger/ButtonBurger.test.tsx, src/ui/components/atoms/button-burger/ButtonBurger.tsx, src/ui/components/atoms/button-burger/styles.scss, src/ui/components/atoms/button-burger/types/IProps.ts
Como desarrollador, necesito crear y probar un componente de menú burger siguiendo los principios de diseño atómico. El componente debe ser inicialmente presentado en Storybook con todas sus variantes y probado usando Vitest para asegurar su funcionalidad.
=> feature: button burger [SEM-067]

src/ui/components/molecules/login-register-buttons/styles.scss
=> fix: fixed align of buttons [SEM-003]

src/globals/_variables.scss, src/ui/components/atoms/reference-information/Reference.stories.tsx, src/ui/components/atoms/reference-information/Reference.test.jsx, src/ui/components/atoms/reference-information/Reference.tsx, src/ui/components/atoms/reference-information/_mocked/references.json, src/ui/components/atoms/reference-information/styles.scss, src/ui/components/atoms/reference-information/types/IProps.ts
Como usuario quiero que se muestre información acerca de las referencias.
=> [SEM-060] LABEL INFORMACION REFERENCIA

src/globals/_variables.scss, src/ui/components/atoms/label-date/LabelDate.scss, src/ui/components/atoms/label-date/LabelDate.stories.tsx, src/ui/components/atoms/label-date/LabelDate.test.jsx, src/ui/components/atoms/label-date/LabelDate.tsx, src/ui/components/atoms/label-date/types/IProps.ts, src/ui/components/atoms/label-date/utils/dateFormatter.ts
Como usuario necesito informacion acerca de la fecha del vol.
=> [SEM-054]: LABEL FECHA

src/ui/components/atoms/icon-upload/IconUpload.scss, src/ui/components/atoms/icon-upload/IconUpload.test.tsx, src/ui/components/atoms/icon-upload/IconUpload.tsx, src/ui/components/molecules/article-publish/ArticlePublish.scss, src/ui/components/molecules/article-publish/ArticlePublish.stories.tsx, src/ui/components/molecules/article-publish/ArticlePublish.test.tsx, src/ui/components/molecules/article-publish/ArticlePublish.tsx, src/ui/components/molecules/article-publish/types/IProps.ts
Como usuario, quiero ver un componente que incluya un botón seguido de una imagen, para que pueda publicar un artículo de manera intuitiva y visualmente atractiva.
=> [SEM-030]: Publicar Artículo

src/ui/components/atoms/label-date/LabelDate.stories.tsx, src/ui/components/atoms/label-date/LabelDate.test.jsx, src/ui/components/atoms/label-date/LabelDate.tsx, src/ui/components/atoms/label-date/utils/dateFormatter.ts
Como usuario necesito informacion acerca de la fecha del vol.
=> [SEM-054]: FIX - LABEL DATE

src/ui/components/atoms/button-with-variants/ButtonWithVariants.scss, src/ui/components/atoms/button-with-variants/ButtonWithVariants.stories.tsx, src/ui/components/atoms/button-with-variants/ButtonWithVariants.test.jsx, src/ui/components/atoms/button-with-variants/ButtonWithVariants.tsx, src/ui/components/atoms/button-with-variants/types/IProps.tsx
added atomic component variant button SEM[072]
=> [SEM-072]: added atomic component variant button

src/globals/_fonts.scss, src/ui/components/atoms/Author-Label/styles.scss, src/ui/components/atoms/label-date/LabelDate.scss, src/ui/components/atoms/logo/style.scss, src/ui/components/atoms/social-media-button/Button.scss, src/ui/components/molecules/option-menu/OptionMenu.stories.tsx, src/ui/components/molecules/option-menu/OptionMenu.test.tsx, src/ui/components/molecules/option-menu/OptionMenu.tsx, src/ui/components/molecules/option-menu/styles.scss, src/ui/components/molecules/option-menu/types/IProps.ts
Como usuario, quiero ver una lista de opciones asociadas con un artículo, para poder compartir el artículo, ver las referencias, acceder a la galería de imágenes y que me lleve al apartado pdf del documento.
=> [SEM-019]:Listado de Opciones

src/ui/components/atoms/Tags/Tags.scss, src/ui/components/atoms/Tags/Tags.stories.tsx, src/ui/components/atoms/Tags/Tags.tsx, src/ui/components/atoms/Tags/types/IProps.ts, src/ui/components/atoms/button-burger/ButtonBurger.module.scss, src/ui/components/molecules/side-panel/mobile-side-pandel/MSPanel.scss, src/ui/components/molecules/side-panel/mobile-side-pandel/MSPanel.stories.tsx, src/ui/components/molecules/side-panel/mobile-side-pandel/MSPanel.test.tsx, src/ui/components/molecules/side-panel/mobile-side-pandel/MSPanel.tsx, src/ui/components/molecules/side-panel/mobile-side-pandel/types/IProps.ts, src/ui/components/molecules/side-panel/panel/SPanel.scss, src/ui/components/molecules/side-panel/panel/SPanel.stories.tsx, src/ui/components/molecules/side-panel/panel/SPanel.test.tsx, src/ui/components/molecules/side-panel/panel/SPanel.tsx, src/ui/components/molecules/side-panel/panel/types/IProps.ts
Como usuario, quiero ver un componente lateral que liste diferentes tags, para poder acceder fácilmente a diferentes temas o categorías del sitio.
=> [SEM-016]: added molecule component side-panel 

src/ui/components/atoms/thumbnail/Thumbnail.stories.tsx, src/ui/components/molecules/volume/Volume.scss, src/ui/components/molecules/volume/Volume.stories.tsx, src/ui/components/molecules/volume/Volume.test.tsx, src/ui/components/molecules/volume/Volume.tsx, src/ui/components/molecules/volume/types/IProps.ts
Como usuario, quiero ver un carrusel de volúmenes de artículos para explorar fácilmente diferentes ediciones o volúmenes de contenido.
=> SEM - 007 Componente Volúmen 

src/globals/_mixins.scss, src/ui/components/atoms/Tags/Tags.scss, src/ui/components/atoms/button/styles.scss, src/ui/components/atoms/divider/Divider.module.scss, src/ui/components/atoms/divider/Divider.test.jsx, src/ui/components/atoms/divider/Divider.tsx, src/ui/components/atoms/thumbnail/Thumbnail.module.scss, src/ui/components/atoms/thumbnail/Thumbnail.tsx, src/ui/components/molecules/side-panel/mobile-side-pandel/MSPanel.scss, src/ui/components/molecules/side-panel/panel/SPanel.scss
Utilizando el nuevo enfoque para aislar los estilos basados en CSS Modules, refactoriza los componentes SEM-065y SEM-066 y modifica sus estilos.
=> [SEM - 315-bis] Refactor, isolar los estilos de los componentes SEM-065 & SEM-066

src/ui/components/molecules/volume-list/VolumeList.scss, src/ui/components/molecules/volume-list/VolumeList.stories.tsx, src/ui/components/molecules/volume-list/VolumeList.test.jsx, src/ui/components/molecules/volume-list/VolumeList.tsx, src/ui/components/molecules/volume-list/__mock__/datamock.json, src/ui/components/molecules/volume-list/types/IProps.ts
Como usuario, quiero ver un listado de volúmenes de artículos claramente organizado y accesible, para poder seleccionar y acceder fácilmente a los diferentes volúmenes disponibles.
=> SEM - 026 Listado de Volúmenes

src/ui/components/molecules/references/References.scss, src/ui/components/molecules/references/References.stories.tsx, src/ui/components/molecules/references/References.test.tsx, src/ui/components/molecules/references/References.tsx, src/ui/components/molecules/references/types/IProps.tsx
added molecule component references
=> SEM[018]: added molecule component references

package-lock.json, src/globals/_mixins.scss, src/ui/components/atoms/Author-Label/AuthorLabel.module.scss, src/ui/components/atoms/article-title/ArticleTitle.scss, src/ui/components/atoms/label-date/LabelDate.scss, src/ui/components/atoms/label-featured-articles/LabelFeaturedArticles.module.scss, src/ui/components/atoms/label-featured-articles/LabelFeaturedArticles.scss, src/ui/components/atoms/points-divider/PointsDivider.scss, src/ui/components/atoms/variable-button/variableButton.module.scss, src/ui/components/molecules/featured-article/FeaturedArticle.scss, src/ui/components/molecules/featured-article/FeaturedArticle.stories.tsx, src/ui/components/molecules/featured-article/FeaturedArticle.test.tsx, src/ui/components/molecules/featured-article/FeaturedArticle.tsx, src/ui/components/molecules/featured-article/types/IProps.ts, yarn.lock
Como usuario, quiero ver los artículos destacados en la página para estar informado de las tendencias de la página.
=> [SEM - 006]:Artículos Destacados 

src/ui/components/atoms/icon-button/types/IProps.ts, src/ui/components/molecules/pdf-share-buttons/PdfShareButton.scss, src/ui/components/molecules/pdf-share-buttons/PdfShareButton.stories.tsx, src/ui/components/molecules/pdf-share-buttons/PdfShareButton.test.tsx, src/ui/components/molecules/pdf-share-buttons/PdfShareButton.tsx, src/ui/components/molecules/pdf-share-buttons/types/IProps.tsx
added molecule pdf/share buttons component
=> SEM[033]: added molecule pdf/share buttons component

src/globals/_breakpoints.scss, src/ui/components/atoms/divider-variables/DividerVariables.stories.tsx, src/ui/components/atoms/divider-variables/DividerVariables.test.jsx, src/ui/components/atoms/divider-variables/DividerVariables.tsx, src/ui/components/atoms/divider-variables/styles.scss, src/ui/components/atoms/label-resources-page/LabelResourcesPage.stories.tsx, src/ui/components/atoms/label-resources-page/LabelResourcesPage.test.jsx, src/ui/components/atoms/label-resources-page/LabelResourcesPage.tsx, src/ui/components/atoms/label-resources-page/styles.scss, src/ui/components/atoms/label-resources-page/types/IProps.ts, src/ui/components/molecules/footer-variables/FooterVariables.stories.tsx, src/ui/components/molecules/footer-variables/FooterVariables.test.jsx, src/ui/components/molecules/footer-variables/FooterVariables.tsx, src/ui/components/molecules/footer-variables/styles.scss
=> [SEM-049]: footer variables, divider and label (resources/page) 

src/ui/components/molecules/LoginPage/LoginPage.scss, src/ui/components/molecules/LoginPage/LoginPage.stories.tsx, src/ui/components/molecules/LoginPage/LoginPage.test.tsx, src/ui/components/molecules/LoginPage/LoginPage.tsx, src/ui/components/molecules/LoginPage/types/IProps.ts
Historia de Usuario
- Como usuario**, quiero ver un botón "Iniciar" y el logo de la empresa en la página de inicio de sesión para identificar claramente la acción de inicio de sesión y reconocer la marca.
=> adding 012 molecule awaiting review

src/middleware/loadEnvs.ts, src/pages/articles/index.astro, src/types/locals.d.ts
Este ticket tiene como objetivo estandarizar las llamadas a Strapi a través de Astro.locals.collections.
=> [SEM-403]: Conexiones de Strapi

src/ui/components/organisms/homepage/HomePage.scss, src/ui/components/organisms/homepage/HomePage.stories.tsx, src/ui/components/organisms/homepage/HomePage.test.jsx, src/ui/components/organisms/homepage/HomePage.tsx, src/ui/components/organisms/homepage/__mock__/datamock.json, src/ui/components/organisms/homepage/types/IProps.ts, yarn.lock
Como usuario quiero una pagina donde se muestre el contenido de manera general.
=> [SEM-401] HOMEPAGE (2/3)

src/ui/components/atoms/icon-button/IconButton.scss, src/ui/components/atoms/variable-button/variableButton.module.scss, src/ui/components/molecules/buttons-pdf-share/ButtonsPdfShare.scss, src/ui/components/molecules/buttons-pdf-share/ButtonsPdfShare.stories.tsx, src/ui/components/molecules/buttons-pdf-share/ButtonsPdfShare.test.tsx, src/ui/components/molecules/buttons-pdf-share/ButtonsPdfShare.tsx, src/ui/components/molecules/buttons-pdf-share/types/IProps.ts, yarn.lock
Como usuario, quiero tener la opción de ver un documento completo y poder compartir el artículo fácilmente para que pueda acceder al documento en un formato familiar y distribuirlo a otros.
=> Botones, pdf y enlace para compartir[SEM-010]

src/ui/components/molecules/pdf-share-buttons/PdfShareButton.scss, src/ui/components/molecules/pdf-share-buttons/PdfShareButton.stories.tsx, src/ui/components/molecules/pdf-share-buttons/PdfShareButton.test.tsx, src/ui/components/molecules/pdf-share-buttons/PdfShareButton.tsx, src/ui/components/molecules/pdf-share-buttons/types/IProps.tsx
fix molecule component pdf/share buttons SEM[033]
=> SEM[033]: fix molecule component pdf/share buttons

src/ui/components/molecules/footer-variables/styles.scss, src/ui/components/molecules/recent-articles-image/RecentArticlesImage.stories.tsx, src/ui/components/molecules/recent-articles-image/RecentArticlesImage.test.jsx, src/ui/components/molecules/recent-articles-image/RecentArticlesImage.tsx, src/ui/components/molecules/recent-articles-image/styles.scss, src/ui/components/molecules/recent-articles-image/types/IProps.ts
=> [SEM-005] Recent articles and image 

src/ui/components/atoms/points-divider/PointsDivider.module.scss, src/ui/components/atoms/points-divider/PointsDivider.test.jsx, src/ui/components/atoms/points-divider/PointsDivider.tsx
Utilizando el nuevo enfoque para aislar los estilos basados en CSS Modules, refactoriza los componentes SEM-071y SEM-073 y modifica sus estilos.
=> refactor to sem 073 waiting for sem 071 to be added to main

src/ui/components/atoms/button-number/ButtonNumber.module.scss, src/ui/components/atoms/button-number/ButtonNumber.stories.tsx, src/ui/components/atoms/button-number/ButtonNumber.test.jsx, src/ui/components/atoms/button-number/ButtonNumber.tsx, src/ui/components/atoms/button-number/types/IProps.ts
New component Button Number Created
**Descripción:**  Peso 5
Botones con números usados en paginación o selección cuantitativa.
**Tareas:**
=> Frontend #243 - Number Button

src/globals/styles/padding.scss, src/globals/styles/tokens.scss
=> FRONTEND-230: add padding scale 

src/library/component/atoms/text-content/TextContent.module.scss, src/library/component/atoms/text-content/TextContent.stories.tsx, src/library/component/atoms/text-content/TextContent.test.tsx, src/library/component/atoms/text-content/TextContent.tsx, src/library/component/atoms/text-content/types/IProps.ts, src/library/component/atoms/text-title/TextTitle.module.scss, src/library/component/atoms/text-title/TextTitle.stories.tsx, src/library/component/atoms/text-title/TextTitle.test.tsx, src/library/component/atoms/text-title/TextTitle.tsx, src/library/component/atoms/text-title/types/IProps.ts, src/library/component/molecules/text-arrangement/TextArrangement.module.scss, src/library/component/molecules/text-arrangement/TextArrangement.stories.tsx, src/library/component/molecules/text-arrangement/TextArrangement.test.tsx, src/library/component/molecules/text-arrangement/TextArrangement.tsx, src/library/component/molecules/text-arrangement/types/IProps.ts
**Description**
The TextArrangement component was created to present text content with multiple layouts and customization options.
**Summary**
- Support for different visual layouts: featured, columns, cards and standard.
- Text alignment control using props.
- Responsive layout that adapts to different devices and content densities.
- Storybook documentation with various examples.
- Pruebas unitarias para verificar la correcta renderización según layout.
- Pruebas de accesibilidad para asegurar una estructura semántica adecuada.
#336
=> feat: add TextArrangement component with layouts, responsiveness, and tests

.github/workflows/publish.yml, src/ui/components/organisms/demo-branch-story/demo-branch-story.stories.tsx, src/ui/components/organisms/demo-branch-story/demo-branch-story.tsx
This pull request updates the `.github/workflows/publish.yml` file to enhance the Storybook deployment process by introducing branch name sanitization and conditional deployment logic. These changes ensure compatibility with branch names containing special characters and provide a clear URL for accessing the deployed Storybook.
* **Branch name sanitization**:
- Added a new step, `Sanitize Branch name`, to sanitize branch names by replacing special characters with hyphens. The sanitized branch name is stored as an output for later use.
- Declared `SANITIZED_BRANCH_NAME` as an output of the job to make it accessible in subsequent steps.
* **Conditional deployment**:
- Added a step to deploy Storybook to a branch corresponding to the sanitized branch name if the current branch is not `main`. …
=> feat: Adding storybook deploy for each evironment

src/globals/_variables.scss, src/ui/components/atoms/label-recent-articles/LabelRecentsArticles.module.scss, src/ui/components/atoms/publish-button/PublishButton.module.scss, src/ui/components/atoms/variable-button/variableButton.module.scss, src/ui/components/organisms/sectiontwo-page/SectiontwoPage.scss
=> FRONTEND-379: fix the colors
